# Generated by Django 5.0.2 on 2024-02-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_staff_options_staff_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
    ]
