# Generated by Django 5.0.2 on 2024-03-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='staff',
            new_name='support_contact',
        ),
    ]
